FROM ubuntu:20.04

ARG PACKAGE=google-chrome-stable
ARG INSTALL_DIR=chrome

RUN     apt-get update && \
        apt-get -y --no-install-recommends install gconf-service \
         libasound2 \
         libatk1.0-0 \
         libc6 \
         libcairo2 \
         libcups2 \
         libdbus-1-3 \
         libdrm2 \
         libexpat1 \
         libfontconfig1 \
         libfreetype6 \
         libgbm1 \
         libgcc1 \
         libgconf-2-4 \
         libgdk-pixbuf2.0-0 \
         libglib2.0-0 \
         libgtk2.0-0 \
         libgtk-3-0 \
         libnspr4 \
         libnss3 \
         libpango1.0-0 \
         libstdc++6 \
         libx11-6 \
         libx11-xcb1 \
         libxcb1 \
         libxcomposite1 \
         libxcursor1 \
         libxdamage1 \
         libxext6 \
         libxfixes3 \
         libxi6 \
         libxrandr2 \
         libxrender1 \
         libxss1 \
         libxtst6 \
         ca-certificates \
         fonts-liberation \
         libappindicator3-1 \
         libnss3 \
         lsb-base \
         xdg-utils \
         libcurl4 \
         iproute2 \
         wget 
RUN      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
         dpkg -i --force-depends google-chrome-stable_current_amd64.deb && \
         rm google-chrome-stable_current_amd64.deb && \
         google-chrome --version && \
         rm -Rf /tmp/* && \
         rm -Rf /var/lib/apt/lists/*

COPY ./chromedriver /usr/bin/chromedriver
RUN chmod -R 755 /usr/bin/chromedriver


COPY ./config/browsers-bin.json /etc/selenoid/browsers.json

COPY ./selenoid /usr/bin/selenoid
RUN chmod -R 755 /usr/bin/selenoid

EXPOSE 4444
ENTRYPOINT ["/usr/bin/selenoid", "-listen", ":4444", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video/"]