version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$CONFIGDIR/config:/etc/selenoid" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$CONFIGDIR/video/1:/opt/selenoid/video"
      - "$CONFIGDIR/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$CONFIGDIR/video/1
    links:
      - ies-test
    command: ["-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  ies-test:
    #image: "vitacore/ies:latest"
    image: $IMAGE
    network_mode: bridge
    ports:
      - "80:80"
#  test-ies-dev:
#    build:
#      context: .
#      dockerfile: Dockerfile-test 
#    network_mode: bridge
#    links:
#      - selenoid
#      - web
