# add to pipeline variable $(PAT_TFS) = token for vitacoredo
#                          $(rsa-tfsbuild) = public key for tfsbuild
# load secure file to Azure->Pipelines->library rsa-tfsbuild = private key for tfsbuild 
#                   
name: git_sync_$(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger: 
#- ci
- '*'

variables:
  github_url: https://$(PAT_TFS)@github.com/vitacore-company/ies-tests.git
  git_url: ssh://tfs:22/tfs/IES.Web.Tests/_git/IES.Web.Tests
  git_directory: IES.Web.Tests

jobs:
- job: GitSyncToGithubCom
  pool:
    name: IES-WEB
  workspace: 
    clean: all
  steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: 'tfs ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCdgH9tMgJ9vIK28PbbNRhDu5P4bNR8ITPcjiOXjoTov/BQ9HtbBRyH2QabvhFoK4YVG+GyLcOuUTuHFDu01Xv5KvSeB+XlI86cIVtdqmfQzOb0Z8tLEJ9AvElMOSvfsR7teAcoVGRCtBTlRItnHNWEtAu7/j31eht/ZXd/4hhNJseoJuDeBGmvBQH4n40rwy6Sy1f53oGRWBFuue+UHasQw9Ao7xyeIVWqnEkmgUq1A6/BGgVZzW7gK4ICqiRYRoak1FawVq8waZNFPpQJKAg7vGI1ryxWvS2aBObVucw02frDdgunzB2RSg+FPQ+EXEbqNH41u1cOvvtSDF5Umd7'
      sshPublicKey: '$(rsa-tfsbuild)'
      sshKeySecureFile: 'rsa-tfsbuild'
    displayName: 'Install an SSH key'

  - script: ssh-keyscan -t rsa tfs >> ~/.ssh/known_hosts
    displayName: Install key
    enabled: false
    
  - checkout: self

  - script: |
      cd ~
      ls -la
      mkdir ./AzureRepos
      cd ~/AzureRepos
      git clone --mirror $(GIT_URL) ./$(GIT_DIRECTORY)
      cd ./$(GIT_DIRECTORY)
      ls -la
      git remote add --mirror=fetch secondary $(GITHUB_URL)
      git fetch origin
      git push secondary --all
    displayName: 'Fetch and Push code to github.com'
