
# add to pipeline variable $(PAT_TFS) = token for vitacoredo
#                         
name: git_sync_$(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger: 
#- ci
- '*'

variables:
  github_url: https://$(PAT_TFS)@github.com/vitacore-company/ies-tests.git
  git_url: ssh://tfs:22/tfs/IES.Web.Tests/_git/IES.Web.Tests
  git_directory: IES.Web.Tests

jobs:
- job: GitSyncToGithubCom
  pool:
    name: IES-WEB
  workspace: 
    clean: all
  steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: 'tfs'
      sshPublicKey: '$(ssh-TFS-GitHub)'
      sshKeySecureFile: 'ssh-TFS-GitHub'
    displayName: 'Install an SSH key'

  - script: ssh-keyscan -t rsa tfs >> ~/.ssh/known_hosts
    displayName: Install key
  - checkout: self

  - script: |
      cd ~
      ls -la
      mkdir ./AzureRepos
      cd ~/AzureRepos
      
      git clone --mirror $(GIT_URL) ./$(GIT_DIRECTORY)
      cd ./$(GIT_DIRECTORY)
      ls -la
    displayName: 'Fetch and Push code to github.com'
